import { Agente } from './agente';
import { AsignaPrestaciones } from './asigna-prestaciones';
import { AsignaPropiedadCliente } from './asigna-propiedad-cliente';
import { Condicion } from './condicion';
import { DatosAdicionales } from './datos-adicionales';
import { DetalleFotosPropiedad } from './detalle-fotos-propiedad';
import { DetallePropiedadDocumento } from './detalle-propiedad-documento';
import { Estado } from './estado';
import { Tipo } from './tipo';
import { Ubicacion } from './ubicacion';
import { Venta } from './venta';
import { Cliente } from './cliente';
import { Moneda } from './moneda';

export class Propiedad {
    idPropiedad: string;
	titulo: string = null;
	tipo: Tipo = new  Tipo();
	condicion: Condicion = new  Condicion();
	estado: Estado = new  Estado();
	ubicacion: Ubicacion= new  Ubicacion();
	moneda: Moneda = new Moneda();
	precio: number = null;
	tamanoArea: number = null;
	direccion: string = null;
	anioConstruccion: number = null;
	descripcion: string= null;
	foto: string =null;
	video: string =null;
	tour: string =null;
    fechaIngreso: Date = null;
    fechaActualizacion: Date = null;
	comentario: string= null;
	distribucion: string = null;
	dormitorios: number = null;
	banios: number= null;
	cocheras: number= null;
	monedamantenimiento: Moneda = new Moneda();
	mantenimiento: number = null;
	cuartosServicio: number= null;
	baniosServicio: number= null;
	pisoPosicion: number= null;
	cantidadPisos: number= null;
	ambientes: string= null;
	oficinasPrivadas: number= null;
	salasReunion: number= null;
	estadoOficina: string= null;
	depositos: number= null;
	zonificacion: string = null;
	linderosFrente: number= null;
	linderosFondo: number= null;
	cantidadOficinas: number= null;
    techoTijeral: number= null;
	patioManiobras: number= null;
	naveIndustrial: number= null;
	linderosIzquierda: number= null;
	linderosDerecha: number= null;
	perimetro: number= null;
	frontis: number= null;
	areaConstruida: number= null;
	areaOcupada: number= null;
	areaAires: number= null;
	ascensores: number= null;
	agente: Agente = new  Agente();
	cliente: Cliente = new  Cliente();
    listaDatosAdicionales: DatosAdicionales[] = [];
    listaAsignaPrestaciones: AsignaPrestaciones[] = [];
    listaDetalleFotosPropiedad: DetalleFotosPropiedad[] = [];
    listaDetallePropiedadDocumentos: DetallePropiedadDocumento[] = [];
    listaAsignaPropiedadCliente: AsignaPropiedadCliente[] = [];
    listaVenta: Venta[] = [];
}
